window.APP_DATA = {
  cities: [
    "İstanbul", "Ankara", "İzmir", "Bursa", "Antalya", "Adana", "Konya", "Gaziantep", "Kocaeli", "Mersin", "Samsun", "Trabzon", "Kayseri", "Eskişehir", "Muğla", "Balıkesir", "Kastamonu"
  ],
  categories: [
    { id: "telefon", label: "Cep Telefonu" },
    { id: "bilgisayar", label: "Bilgisayar" },
    { id: "vasita", label: "Vasıta" },
    { id: "ev-esyasi", label: "Ev Eşyası" },
    { id: "kamera", label: "Fotoğraf & Kamera" },
    { id: "oyuncu", label: "Oyuncu Ekipmanları" },
    { id: "spor", label: "Spor & Outdoor" },
    { id: "mobilya", label: "Mobilya" }
  ],
  demoUser: {
    id: "demo-user-1",
    fullName: "Metehan E.",
    email: "demo@pazarium.com",
    password: "demo123",
    phone: "0532 000 00 00",
    city: "Kastamonu"
  },
  listings: [
    {
      id: "l1",
      title: "iPhone 14 Pro 128 GB - Hatasız, Kutu Faturalı",
      price: 42950,
      oldPrice: 44800,
      category: "telefon",
      city: "İstanbul",
      district: "Kadıköy",
      label: "Öne Çıkan",
      condition: "İkinci El",
      brand: "Apple",
      model: "iPhone 14 Pro",
      year: 2023,
      status: "Yeni Gibi",
      description: "Cihaz tertemiz kullanıldı. Kozmetik olarak çok iyi durumda, ekranında kırık ya da çatlak yok. Pil sağlığı iyi seviyede. Kutu, kablo ve fatura mevcut. Elden teslim önceliklidir.",
      seller: { name: "Selin Kaya", phone: "0554 210 66 91", memberSince: "2021", score: 4.9 },
      images: ["assets/images/phone-1.svg", "assets/images/phone-2.svg", "assets/images/phone-3.svg"],
      features: ["Face ID", "128 GB", "Pil Sağlığı %89", "Türkiye Cihazı"],
      publishedAt: "Bugün",
      isFeatured: true,
      ownerId: "seed-1"
    },
    {
      id: "l2",
      title: "MacBook Air M2 13.6 - 8/256 - Çok Temiz",
      price: 33600,
      oldPrice: 34990,
      category: "bilgisayar",
      city: "Ankara",
      district: "Çankaya",
      label: "Hızlı Satış",
      condition: "İkinci El",
      brand: "Apple",
      model: "MacBook Air M2",
      year: 2024,
      status: "Yeni Gibi",
      description: "Ofis kullanımı için alındı. Sadece birkaç ay kullanıldı. Şarj döngüsü düşük, kozmetik kusursuz. Kutu ve aksesuarları tam.",
      seller: { name: "Eren Bilgiç", phone: "0543 111 10 10", memberSince: "2020", score: 4.8 },
      images: ["assets/images/laptop-1.svg", "assets/images/laptop-2.svg", "assets/images/laptop-3.svg"],
      features: ["M2 İşlemci", "Retina Ekran", "8 GB RAM", "256 GB SSD"],
      publishedAt: "Dün",
      isFeatured: true,
      ownerId: "seed-2"
    },
    {
      id: "l3",
      title: "Volkswagen Golf 1.5 TSI Life DSG - Boyasız",
      price: 1195000,
      oldPrice: 1230000,
      category: "vasita",
      city: "İzmir",
      district: "Bornova",
      label: "Kurumsal",
      condition: "İkinci El",
      brand: "Volkswagen",
      model: "Golf",
      year: 2022,
      status: "Ekspertiz Hazır",
      description: "Araçta değişen yoktur. Düzenli servis bakımlı, düşük kilometreli ve masrafsızdır. İstenilen serviste ekspertize açıktır.",
      seller: { name: "Altın Yol Otomotiv", phone: "0536 887 44 00", memberSince: "2018", score: 5.0 },
      images: ["assets/images/car-1.svg", "assets/images/car-2.svg", "assets/images/car-3.svg"],
      features: ["79.000 km", "Otomatik", "Benzin", "Yetkili Servis Bakımlı"],
      publishedAt: "2 gün önce",
      isFeatured: true,
      ownerId: "seed-3"
    },
    {
      id: "l4",
      title: "L Koltuk Takımı - Yıkanabilir Kumaş - Az Kullanıldı",
      price: 18400,
      oldPrice: 19900,
      category: "mobilya",
      city: "Bursa",
      district: "Nilüfer",
      label: "Fırsat",
      condition: "İkinci El",
      brand: "Vivense",
      model: "L Koltuk",
      year: 2023,
      status: "Temiz",
      description: "Salon değişikliği nedeniyle satılıktır. Kumaşı sökülüp yıkanabiliyor. Çökme, yırtık veya leke yok. Ölçüler detayda paylaşılır.",
      seller: { name: "Ayşe Şimşek", phone: "0531 224 12 31", memberSince: "2022", score: 4.7 },
      images: ["assets/images/sofa-1.svg", "assets/images/sofa-2.svg", "assets/images/sofa-3.svg"],
      features: ["Yıkanabilir Kumaş", "Modern Tasarım", "Geniş Oturum", "Az Kullanıldı"],
      publishedAt: "3 gün önce",
      isFeatured: false,
      ownerId: "seed-4"
    },
    {
      id: "l5",
      title: "Sony A7 III + 28-70 Lens - Shutter Düşük",
      price: 51400,
      oldPrice: 53250,
      category: "kamera",
      city: "Antalya",
      district: "Muratpaşa",
      label: "Vitrin",
      condition: "İkinci El",
      brand: "Sony",
      model: "A7 III",
      year: 2023,
      status: "Profesyonel",
      description: "Fotoğraf stüdyosunda yedek gövde olarak kullanıldı. Shutter düşük, kozmetik temiz. Lens ve batarya dahil. İstenirse örnek çekim paylaşılır.",
      seller: { name: "Mert Yalın", phone: "0544 901 20 00", memberSince: "2019", score: 4.9 },
      images: ["assets/images/camera-1.svg", "assets/images/camera-2.svg", "assets/images/camera-3.svg"],
      features: ["Full Frame", "4K Video", "Düşük Shutter", "Lens Dahil"],
      publishedAt: "4 gün önce",
      isFeatured: true,
      ownerId: "seed-5"
    },
    {
      id: "l6",
      title: "PlayStation 5 Slim + 2 Kol + FIFA 25",
      price: 23900,
      oldPrice: 24990,
      category: "oyuncu",
      city: "Kocaeli",
      district: "İzmit",
      label: "Kaçırma",
      condition: "İkinci El",
      brand: "Sony",
      model: "PS5 Slim",
      year: 2024,
      status: "Temiz",
      description: "Evde özenli kullanıldı. 2 orijinal kol ve oyun hesabı ile teslim edilecek. Kutusu mevcut, cihazda hiçbir sorun yok.",
      seller: { name: "Can Güneş", phone: "0507 980 45 45", memberSince: "2023", score: 4.6 },
      images: ["assets/images/console-1.svg", "assets/images/console-2.svg", "assets/images/console-3.svg"],
      features: ["2 Kol", "Kutulu", "Oyun Dahil", "Temiz Kullanım"],
      publishedAt: "5 gün önce",
      isFeatured: false,
      ownerId: "seed-6"
    },
    {
      id: "l7",
      title: "Elektrikli Katlanır Bisiklet - 45 km Menzil",
      price: 27150,
      oldPrice: 28500,
      category: "spor",
      city: "Eskişehir",
      district: "Tepebaşı",
      label: "Yeni İlan",
      condition: "İkinci El",
      brand: "Volta",
      model: "VSM",
      year: 2024,
      status: "Bakımlı",
      description: "Şehir içi kullanım için idealdir. Katlanabilir yapıdadır. Batarya sağlığı iyi, lastikler yenidir. Şarj cihazı ile verilecektir.",
      seller: { name: "Burak Çelik", phone: "0535 772 22 19", memberSince: "2021", score: 4.8 },
      images: ["assets/images/bike-1.svg", "assets/images/bike-2.svg", "assets/images/bike-3.svg"],
      features: ["45 km Menzil", "Katlanabilir", "Şarj Cihazı Dahil", "Bakımlı"],
      publishedAt: "1 hafta önce",
      isFeatured: false,
      ownerId: "seed-7"
    },
    {
      id: "l8",
      title: "Samsung 55'' 4K Smart TV - Kumandalı",
      price: 17200,
      oldPrice: 18150,
      category: "ev-esyasi",
      city: "Trabzon",
      district: "Ortahisar",
      label: "Öne Çıkan",
      condition: "İkinci El",
      brand: "Samsung",
      model: "55AU9000",
      year: 2022,
      status: "Çiziksiz",
      description: "Taşınma nedeniyle satılıyor. Panel sorunsuz, ölü piksel yok. Kumanda ve ayakları mevcut. İstenirse duvar aparatı da verilir.",
      seller: { name: "Zeynep Kılıç", phone: "0532 770 33 88", memberSince: "2020", score: 4.9 },
      images: ["assets/images/tv-1.svg", "assets/images/tv-2.svg", "assets/images/tv-3.svg"],
      features: ["4K UHD", "Smart TV", "Wi‑Fi", "Kumandalı"],
      publishedAt: "1 hafta önce",
      isFeatured: true,
      ownerId: "seed-8"
    }
  ]
};